APIVersion: v1.7.1
name: welcomehelsinki
type: wordpress
docroot: web
php_version: "7.4"
webserver_type: nginx-fpm
router_http_port: "80"
router_https_port: "443"
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
mariadb_version: "10.2"
webcache_enabled: false
provider: default
upload_dir: web/app/uploads
working_dir:
  web: /var/www/html
  db: /home
